import {
  AnalyticsSnapshot,
  AppState,
  Assignment,
  CalendarEvent,
  Classroom,
  ChatMessage,
  DiscussionThread,
  NotificationItem,
  ResourceItem,
  UserAccount,
} from './types';

export const STORAGE_KEY = 'nexus-lms-state';
export const SESSION_KEY = 'nexus-lms-session';
export const PREFERENCES_KEY = 'nexus-lms-preferences';

const PASSWORD_HASH = '978c26d91294fd7eba1798cb475d5da104f51a787c5b25e3940b26ec940c4d9a';

export const seededUsers: UserAccount[] = [
  {
    id: 'user-student',
    name: 'Alex Rivers',
    email: 'alex@nexus.dev',
    role: 'student',
    title: 'Product Design Student',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?q=80&w=300&auto=format&fit=crop',
    bio: 'Design systems student focused on accessible interfaces and faster feedback loops.',
    locale: 'en-US',
    xp: 1280,
    badges: ['Fast Learner', 'Discussion Leader', '7 Day Streak'],
    passwordHash: PASSWORD_HASH,
  },
  {
    id: 'user-teacher',
    name: 'Sarah Jenkins',
    email: 'sarah@nexus.dev',
    role: 'teacher',
    title: 'Senior Instructor',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?q=80&w=300&auto=format&fit=crop',
    bio: 'Teaches front-end architecture, collaboration patterns, and rubric-driven assessment.',
    locale: 'en-US',
    xp: 2140,
    badges: ['Top Mentor', 'Course Builder', 'AI Reviewer'],
    passwordHash: PASSWORD_HASH,
  },
  {
    id: 'user-admin',
    name: 'Noah Patel',
    email: 'admin@nexus.dev',
    role: 'admin',
    title: 'Platform Administrator',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=300&auto=format&fit=crop',
    bio: 'Oversees schools, permissions, analytics, and platform security policies.',
    locale: 'en-US',
    xp: 3260,
    badges: ['Security Lead', 'Platform Owner', 'Incident Ready'],
    passwordHash: PASSWORD_HASH,
  },
];

export const seededClasses: Classroom[] = [
  {
    id: 'class-design',
    code: 'NX-2048',
    title: 'Advanced UI Systems',
    subject: 'Design',
    section: 'Section A',
    teacherId: 'user-teacher',
    teacherName: 'Sarah Jenkins',
    color: '#7c3aed',
    description: 'Design systems, accessibility patterns, and collaborative critiques.',
    students: 38,
    archived: false,
    progress: 72,
    nextDeadline: 'Today · 3:00 PM',
    meetingTime: 'Tue 10:00 AM',
    tags: ['Design Systems', 'Accessibility', 'Critique'],
    sections: [
      { id: 'design-core', name: 'Core Cohort', studentCount: 24 },
      { id: 'design-advanced', name: 'Advanced Studio', studentCount: 14 },
    ],
    resourceCount: 18,
    unreadMessages: 4,
  },
  {
    id: 'class-frontend',
    code: 'NX-7741',
    title: 'Modern Frontend Architecture',
    subject: 'Engineering',
    section: 'Section B',
    teacherId: 'user-teacher',
    teacherName: 'Sarah Jenkins',
    color: '#2563eb',
    description: 'Component architecture, state management, and deployment workflows.',
    students: 31,
    archived: false,
    progress: 58,
    nextDeadline: 'Tomorrow · 9:00 AM',
    meetingTime: 'Thu 2:00 PM',
    tags: ['React', 'State', 'Performance'],
    sections: [
      { id: 'frontend-live', name: 'Live Build Lab', studentCount: 16 },
      { id: 'frontend-review', name: 'Review Circle', studentCount: 15 },
    ],
    resourceCount: 24,
    unreadMessages: 2,
  },
  {
    id: 'class-ops',
    code: 'NX-9005',
    title: 'Learning Operations',
    subject: 'Administration',
    section: 'School Wide',
    teacherId: 'user-admin',
    teacherName: 'Noah Patel',
    color: '#0f766e',
    description: 'Attendance, policy management, and student support workflows.',
    students: 124,
    archived: false,
    progress: 91,
    nextDeadline: 'Friday · 11:30 AM',
    meetingTime: 'Mon 1:00 PM',
    tags: ['Operations', 'Policy', 'Insights'],
    sections: [
      { id: 'ops-campus', name: 'Campus Team', studentCount: 44 },
      { id: 'ops-support', name: 'Support Team', studentCount: 80 },
    ],
    resourceCount: 11,
    unreadMessages: 0,
  },
];

export const seededAssignments: Assignment[] = [
  {
    id: 'assignment-1',
    classId: 'class-design',
    title: 'Microinteraction Audit',
    kind: 'assignment',
    dueDate: 'Today · 5:00 PM',
    status: 'assigned',
    maxPoints: 100,
    submissions: 19,
    averageScore: 86,
    manualReview: true,
    aiPlagiarismScore: 9,
    description: 'Review three interfaces and annotate where motion can reduce friction.',
    rubric: ['Clarity of examples', 'Actionable feedback', 'Accessibility awareness'],
  },
  {
    id: 'assignment-2',
    classId: 'class-frontend',
    title: 'Component Quiz: State Sync',
    kind: 'quiz',
    dueDate: 'Tomorrow · 11:30 AM',
    status: 'submitted',
    maxPoints: 20,
    submissions: 27,
    averageScore: 18,
    manualReview: false,
    aiPlagiarismScore: 4,
    description: 'Auto-graded quiz covering event flow, state, and effects.',
    rubric: ['Correct answers', 'Reasoning accuracy'],
  },
  {
    id: 'assignment-3',
    classId: 'class-ops',
    title: 'Attendance Forecast Memo',
    kind: 'project',
    dueDate: 'Friday · 12:00 PM',
    status: 'graded',
    maxPoints: 50,
    submissions: 12,
    averageScore: 44,
    manualReview: true,
    aiPlagiarismScore: 2,
    description: 'Summarize attendance trends and propose interventions.',
    rubric: ['Trend analysis', 'Recommendation quality', 'Presentation'],
  },
];

export const seededDiscussions: DiscussionThread[] = [
  {
    id: 'thread-1',
    classId: 'class-design',
    author: 'Ava Chen',
    role: 'student',
    message: 'Can we get a rubric example for the microinteraction audit? @Sarah',
    time: '8 min ago',
    replies: 4,
    mentions: ['Sarah'],
    pinned: true,
  },
  {
    id: 'thread-2',
    classId: 'class-frontend',
    author: 'Sarah Jenkins',
    role: 'teacher',
    message: 'I posted a starter checklist for the quiz review. Focus on state transitions.',
    time: '34 min ago',
    replies: 7,
    mentions: [],
    pinned: false,
  },
  {
    id: 'thread-3',
    classId: 'class-ops',
    author: 'Noah Patel',
    role: 'admin',
    message: 'Attendance export is now synced with the district feed.',
    time: '1 hr ago',
    replies: 2,
    mentions: [],
    pinned: false,
  },
];

export const seededMessages: ChatMessage[] = [
  {
    id: 'message-1',
    classId: 'class-design',
    sender: 'Sarah Jenkins',
    role: 'teacher',
    message: 'Please post your wireframes in the class folder before tomorrow.',
    time: '9:02 AM',
  },
  {
    id: 'message-2',
    classId: 'class-design',
    sender: 'Alex Rivers',
    role: 'student',
    message: 'Uploaded the first draft. I also added keyboard focus states.',
    time: '9:08 AM',
  },
  {
    id: 'message-3',
    classId: 'class-frontend',
    sender: 'Sarah Jenkins',
    role: 'teacher',
    message: 'Office hours move to 2 PM because of the design review.',
    time: '9:10 AM',
  },
];

export const seededNotifications: NotificationItem[] = [
  {
    id: 'note-1',
    title: 'Assignment due soon',
    description: 'Microinteraction Audit is due in 3 hours.',
    priority: 'high',
    unread: true,
    time: '5m ago',
    kind: 'deadline',
  },
  {
    id: 'note-2',
    title: 'New teacher feedback',
    description: 'Sarah left rubric notes on your latest submission.',
    priority: 'normal',
    unread: true,
    time: '18m ago',
    kind: 'feedback',
  },
  {
    id: 'note-3',
    title: 'Calendar sync',
    description: 'External calendar connected successfully.',
    priority: 'low',
    unread: false,
    time: '1h ago',
    kind: 'integration',
  },
];

export const seededEvents: CalendarEvent[] = [
  {
    id: 'event-1',
    title: 'Microinteraction Review',
    classId: 'class-design',
    date: '2026-05-06',
    startTime: '15:00',
    endTime: '15:30',
    type: 'deadline',
    color: '#7c3aed',
  },
  {
    id: 'event-2',
    title: 'Frontend Office Hours',
    classId: 'class-frontend',
    date: '2026-05-07',
    startTime: '14:00',
    endTime: '15:00',
    type: 'meeting',
    color: '#2563eb',
  },
  {
    id: 'event-3',
    title: 'District Sync Check',
    classId: 'class-ops',
    date: '2026-05-08',
    startTime: '11:30',
    endTime: '12:00',
    type: 'class',
    color: '#0f766e',
  },
];

export const seededResources: ResourceItem[] = [
  {
    id: 'resource-1',
    classId: 'class-design',
    name: 'Critique rubric.pdf',
    type: 'document',
    size: '430 KB',
    updatedAt: 'Today',
    preview: 'Structured rubric for design critiques and peer review.',
  },
  {
    id: 'resource-2',
    classId: 'class-frontend',
    name: 'State machine workshop.mp4',
    type: 'video',
    size: '248 MB',
    updatedAt: 'Yesterday',
    preview: 'Recorded walkthrough of event flow and reducer design.',
  },
  {
    id: 'resource-3',
    classId: 'class-ops',
    name: 'Attendance exports',
    type: 'folder',
    size: '1.8 GB',
    updatedAt: '2 days ago',
    preview: 'District-level reports and term snapshots.',
  },
];

export const analyticsByRole: Record<string, AnalyticsSnapshot> = {
  student: {
    attendance: 94,
    completion: 78,
    engagement: 83,
    averageGrade: 91,
    streak: 7,
    heatmap: [2, 4, 8, 7, 9, 10, 11, 5, 3, 6, 8, 10, 12, 13],
    weeklyProgress: [72, 75, 78, 79, 81, 84, 86],
  },
  teacher: {
    attendance: 97,
    completion: 86,
    engagement: 88,
    averageGrade: 89,
    streak: 12,
    heatmap: [6, 5, 8, 11, 10, 12, 13, 10, 8, 7, 9, 12, 14, 15],
    weeklyProgress: [64, 68, 70, 73, 76, 81, 84],
  },
  admin: {
    attendance: 99,
    completion: 92,
    engagement: 91,
    averageGrade: 93,
    streak: 20,
    heatmap: [10, 11, 12, 13, 14, 15, 14, 13, 12, 11, 12, 13, 14, 15],
    weeklyProgress: [81, 82, 84, 87, 88, 91, 92],
  },
};

export const defaultPreferences = {
  theme: 'dark' as const,
  language: 'English',
  sidebarOpen: false,
  widgetOrder: ['progress', 'classes', 'assignments', 'activity', 'assistant', 'calendar'],
};

export const createInitialState = (): AppState => ({
  session: null,
  preferences: defaultPreferences,
  users: seededUsers,
  classes: seededClasses,
  assignments: seededAssignments,
  discussions: seededDiscussions,
  messages: seededMessages,
  notifications: seededNotifications,
  events: seededEvents,
  resources: seededResources,
});
